apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-01-09T09:46:49Z"
  generation: 1
  name: httpd-frontend
  namespace: default
  resourceVersion: "1560"
  uid: 8146551c-5967-40ac-853c-bb3c262fab98
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: httpd-pod