mkdir -p /etc/kubernetes/manifests/
cat <<EOF >/etc/kubernetes/manifests/static-web.yaml
apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
  labels:
    role: myrole
spec:
  containers:
    - name: static-busybox
      image: busybox:1.28.4
      ports:
        - name: static-busybox
          containerPort: 80
          protocol: TCP
EOF