apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2024-03-05T10:57:58Z"
  name: dev-user-binding
  namespace: blue
  resourceVersion: "718"
  uid: 7d347fcf-964d-4603-806e-920b94acbc0d
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: dev-user